require(plyr)
require(dplyr)

x <- tbl_df(read.table("exdata-data-household_power_consumption/household_power_consumption.txt",sep=";",stringsAsFactors = F,header=T))
y <- x %>% mutate(Date = as.Date(Date,'%d/%m/%Y')) %>% filter(Date >= "2007-02-01", Date <= "2007-02-02") %>% mutate(Global_active_power = as.numeric(Global_active_power),Global_reactive_power = as.numeric(Global_reactive_power),Voltage = as.numeric(Voltage),Global_intensity = as.numeric(Global_intensity),Sub_metering_1 = as.numeric(Sub_metering_1),Sub_metering_2 = as.numeric(Sub_metering_2),Sub_metering_3 = as.numeric(Sub_metering_3),datetime = as.POSIXct(paste(Date,Time)))
png("plot4.png",width = 480,height = 480)
par(mfrow=c(2,2))
plot(y$datetime,y$Global_active_power,xlab="",ylab="Global Active Power",type='l')
plot(y$datetime,y$Voltage,xlab="datetime",ylab="Volatge",type='l')
plot(y$datetime,y$Sub_metering_1,xlab="",ylab='Energy sub metering')
lines(y$datetime,y$Sub_metering_2,col="red",type="l")
lines(y$datetime,y$Sub_metering_3,col="blue",type="l")
legend("topright",col = c("black", "red", "blue"), legend = c("Sub_metering_1",  "Sub_metering_2", "Sub_metering_3"), lty = 1)
plot(y$datetime,y$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="l")
dev.off()