require(plyr)
require(dplyr)

x <- tbl_df(read.table("exdata-data-household_power_consumption/household_power_consumption.txt",sep=";",stringsAsFactors = F,header=T))
y <- x %>% mutate(Date = as.Date(Date,'%d/%m/%Y')) %>% filter(Date >= "2007-02-01", Date <= "2007-02-02") %>% mutate(Global_active_power = as.numeric(Global_active_power),Sub_metering_1 = as.numeric(Sub_metering_1),Sub_metering_2 = as.numeric(Sub_metering_2),Sub_metering_3 = as.numeric(Sub_metering_3),datetime = as.POSIXct(paste(Date,Time)))
png("plot3.png",width = 480,height = 480)
plot(y$datetime,y$Sub_metering_1,type='l', xlab = "", ylab = "Energy sub metering")
lines(y$datetime, y$Sub_metering_2, type = "l", col="red")
lines(y$datetime, y$Sub_metering_3, type = "l", col="blue")
legend("topright",col = c("black", "red", "blue"), legend = c("Sub_metering_1",  "Sub_metering_2", "Sub_metering_3"), lty = 1)
dev.off()
